image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:

  TEST_IMAGE: gitlab.com/summitech/automated-tests/loopmi-java:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: gitlab.com/summitech/automated-tests/loopmi-java:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.com/summitech/automated-tests/loopmi-java

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE mvn test