image: maven:3.3.9-jdk-8

before_script:
  #- apk update && apk add git
  - apt-get update -qq & apt-get install wget
  - wget https://gist.githubusercontent.com/alonisser/11192482/raw/e1d8d4ed579d64902e951e4f9fa487b793035f9b/setup-headless-selenium-xvfb.sh
  - sh setup-headless-selenium-xvfb.sh
  - export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  - /usr/bin/Xvfb :99 -ac -screen 0 1024x768x8
 # - export DISPLAY=:1
  - sleep 3

run_test:
  script:
    - mvn test 