# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind
   - selenium/standalone-chrome:latest

stages:
  - build
  - test

before_script:
  - apt-get update 
  - export DISPLAY=:1
  - sleep 3  

maven-build:
  image: maven:3.3.9-jdk-8
  stage: build
  script: "mvn test"

